In [193]:
import numpy as np

In [194]:
a = np.array([1,6,2,8,3,11,3,10,1,7])
a

array([ 1,  6,  2,  8,  3, 11,  3, 10,  1,  7])

In [195]:
b=a.reshape(5,2)

In [196]:
mean_a = b.mean(axis=0)
mean_a

array([2. , 8.4])

In [197]:
a_centered=b-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [198]:
a_centered_sp=a_centered.T[0]@a_centered.T[1]
a_centered_sp

8.0

In [199]:
c=a_centered[:5,:1]
c

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [200]:
f=a_centered[:5,1:]
f

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [201]:
a_centered_sp=c[0,0]*f[0,0]+c[1,0]*f[1,0]+c[2,0]*f[2,0]+c[3,0]*f[3,0]+c[4,0]*f[4,0]
a_centered_sp

8.0

In [202]:
c=a_centered[:5,:1]
c

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [203]:
ft=f.T
ft

array([[-2.4, -0.4,  2.6,  1.6, -1.4]])

In [204]:
a_centered_sp=ft@c
a_centered_sp

array([[8.]])

In [205]:
a_centered.shape

(5, 2)

In [206]:
a_centered_sp/(a_centered.shape[0]-1)

array([[2.]])